canopus/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stars.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from .views import UserRegisterView, UserEditView, CustomPasswordChangeView, ShowProfilePageView, EditProfilePageView, CreateProfilePageView
from . import views

app_name = 'members'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path('password/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_success/', views.password_success, name='password_success'),
    path('<int:pk>/profile/', ShowProfilePageView.as_view(), name='show_profile_page'),
    path('<int:pk>/edit_profile_page', EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page', CreateProfilePageView.as_view(), name='create_profile_page')
]

stars/urls.py
from django.urls import path
#from . import views
from .views import *

app_name = 'stars'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name='delete_post' ),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('article/<int:pk>/comment', AddCommentView.as_view(), name='add_comment'),
]

stars/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")
    website_url = models.CharField(max_length=255, null=True, blank=True)
    facebook = models.CharField(max_length=255, null=True, blank=True)
    instagram = models.CharField(max_length=255, null=True, blank=True)
    linkedin = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)
    
    def get_absolute_url(self):
        return reverse('home')

class Post(models.Model):
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to="images/")
    title_tag = models.CharField(max_length=255, default="My Awesome Blog")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    snippet = models.CharField(max_length=255)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse('stars:home')


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models. DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

stars/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'title_tag', 'snippet', 'body', 'header_image')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'snippet': forms.TextInput(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'title_tag', 'snippet', 'body')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'snippet': forms.TextInput(attrs={'class':'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class':'form-control'}),
        }

stars/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Comment
from .forms import PostForm, EditForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect

class HomeView(ListView):
    model = Post
    template_name = 'stars/home.html'
    ordering = ['-post_date']

def LikeView(request, pk):
    print(request.POST)
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    print(post)

    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(reverse('stars:article-detail', args=[str(pk)]))

class ArticleDetailView(DetailView):
    model = Post
    template_name = 'stars/article_details.html'

class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'stars/add_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'stars/update_post.html'

class DeletePostView(DeleteView):
    model = Post
    template_name = 'stars/delete_post.html'
    success_url = reverse_lazy('stars:home')


class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'stars/add_comment.html'
    success_url = reverse_lazy('stars:home')
    
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

stars/templates/stars/add_comment.html
{% extends 'stars/base.html' %}
{% block title %}Comment On Blog Post{% endblock %}
{% block content %}

<h1>Add Comment...</h1>
<br><br>

<div class="form-group">
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-secondary">Add Comment</button>
</form>
</div>

{% endblock %}

stars/templates/stars/add_post.html
{% extends 'stars/base.html' %}
{% block title %}Create a New Post{% endblock %}
{% block content %}

<h1>Add Post...</h1>
<br><br>

<div class="form-group">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Post</button>
    </form>
</div>

{% endblock %}

stars/templates/stars/article_details.html
{% extends 'stars/base.html' %}
{% load static %}
{% block title %}
{{ post.title_tag }}
{% endblock %}

{% block content %}

<h1>{{ post.title }}</h1>
<small>By:
    {{ post.author.first_name }}
    {{ post.author.last_name }} -
    {{ post.post_date }}

    {% if user.is_authenticated and user.id == post.author.id %}
    - <a href="{% url 'stars:update_post' post.pk %}">(Edit)</a>
    <a href="{% url 'stars:delete_post' post.pk %}">(Delete)</a>

    {% endif %}

</small><br />
<hr>
<br />
{% if post.header_image %}
<img src="{{ post.header_image.url }}" alt="">
{% endif %}

{{ post.body | safe }}



<br><br>

<form action="{% url 'stars:like_post' post.pk %}" method="POST">
    {% csrf_token %}
    {% if user.is_authenticated %}
    <button type="submit" , name="post_id" , value="{{ post.id }}" , class="btn {% if user in post.likes.all %} btn-primary 
{% else %} btn-outline-primary {% endif %} btn-sm">Like
    </button>
    {% else %}
    <small>Login to like</small>
    {% endif %}
    - {{ post.likes.count }} Likes
</form>

<br>

{% if post.author.profile %}
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-2">
            {% if post.author.profile.profile_pic %}
            <img src="{{ post.author.profile.profile_pic.url }}" class="img-fluid rounded-start" alt="...">
            {% else %}
            <img src="{% static 'stars\images\default_profile_pic.PNG' %}" class="img-fluid rounded-start" alt="...">

            
            {% endif %}
            </div>
        <div class="col-md-10">
            <div class="card-body">
                <h5 class="card-title">
                    {{ post.author.first_name }}
                    {{ post.author.last_name }}
                </h5>
                <p class="card-text">
                    <small class="text-body-secondary">

                        <a href="{% url 'members:show_profile_page' post.author.profile.id %}">Profile Page</a>


                        {% if post.author.profile.website_url %}
                         | <a href="{{ post.author.profile.website_url }}">Website</a>
                        {% endif %}
                        {% if post.author.profile.facebook %}
                         | <a href="{{ post.author.profile.facebook }}">Facebook</a>
                        {% endif %}

                        {% if post.author.profile.instagram %}
                         | <a href="{{ post.author.profile.instagram }}">Instagram</a>
                        {% endif %}

                        {% if post.author.profile.linkedin %}
                         | <a href="{{ post.author.profile.linkedin }}">Linkedin</a>
                        {% endif %}

                    </small>
                </p>
                <p class="card-text">{{ post.author.profile.bio }}</p>

            </div>
        </div>
    </div>
</div>
{% endif %}

<br>
<h2>Comments...</h2>

{% if user.is_authenticated %}
<a href="{% url 'stars:add_comment' post.pk %}">Add Comment</a>
<br><br>
{% endif %}

{% if not post.comments.all %}
    No comments yet...
{% else %}
    {% for comment in post.comments.all %}
        <strong>{{ comment.name }} - {{ comment.date_added }}</strong>
        <br>
        {{ comment.body }}
        <br><br>
    {% endfor %}
{% endif %}

<br><br>

{% endblock %}

stars/templates/stars/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block title %}
    Canopus Star
    {% endblock %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'stars:home' %}">Canopus</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link active" href="{% url 'stars:add_post'%}">Add Post</a>
          </li>

          {% endif %}

        </ul>


        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.first_name }} {{ user.last_name }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end">

              <li><a class="dropdown-item" href="{% url 'members:edit_profile'  %}">Edit settings</a></li>

              {% if user.profile.id %}
              <li><a class="dropdown-item" href="{% url 'members:edit_profile_page' user.profile.id %}">Edit Profile
                  Page</a></li>
              <li><a class="dropdown-item" href="{% url 'members:show_profile_page' user.profile.id %}">Show Profile
                  Page</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'members:create_profile_page' %}">Create Profile Page</a></li>
              {% endif %}
            </ul>
          </li>

          {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'members:register'%}">Register</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>

          {% endif %}
        </ul>


        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <br />

  <div class='container mt-5'>
    {% block content %}
    {% endblock%}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</body>

</html>

stars/templates/stars/delete_post.html
{% extends 'stars/base.html' %}
{% block title %}Delete Post{% endblock %}

{% block content %}

{% if user.is_authenticated and user.id == post.author.id %}

<h1>Delete Post...</h1>
<br><br>
<h3>Delete: {{ post.title }}</h3>

<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        <strong>Are you sure ?</strong>
        <br>
        <br>
        <button class=" btn btn-secondary">Delete Post</button>
    </form>
</div>
{% else %}
<p>You are not allowed here !</p>
{% endif %}

{% endblock %}

stars/templates/stars/home.html
{% extends 'stars/base.html' %}

{% block content %}

{% if object_list %}
<div class="row">
    <div class="col-lg-10">

        <h1>Post</h1>
        <ul class="list-group list-group-flush">
            {% for post in object_list %}
            <li class="list-group-item"><a href="{% url 'stars:article-detail' post.pk %}">{{ post.title }}</a>
                - {{ post.author.first_name }}{{ post.author.last_name }}
                - {{ post.post_date }}

                {% if user.is_authenticated and user.id == post.author.id %}
                <small>
                    - <a href="{% url 'stars:update_post' post.pk %}">(Edit)</a>
                    <a href="{% url 'stars:delete_post' post.pk %}">(Delete)</a>
                </small>
                {% endif %}

                <br>
                {{ post.snippet }}
                <!-- {{ post.body | safe | slice:":200" }} -->
            </li>
            {% endfor %}
        </ul>

    </div>
</div>
{% endif %}
{% endblock %}

stars/templates/stars/update_post.html
{% extends 'stars/base.html' %}
{% block title %}Edit Blog Post{% endblock %}
{% block content %}

<h1>Update Post...</h1>
<br><br>

{% if user.is_authenticated and user.id == post.author.id %}
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Update</button>
    </form>
</div>

{% else %}
<p>You are not allowed here! (and you know it...)</p>
{% endif %}

{% endblock %}